Enhancement/focal support
dnsimple/chef-dnsimple pull request #72
Opened 2021-05-10 19:19 UTC by AGS4NO

Update CI to support focal

Belongs to https://github.com/dnsimple/dnsimple-ops/issues/2550

## :shipit: Deploy Steps:

- [x] Merge and pull latest
- [ ] [Community cookbook release](https://dnsimple.atlassian.net/wiki/spaces/DEV/pages/347242670/Cookbook+Workflow+-+Community#Deploying-Approved-Changes)

## :shipit: Verification Steps

- [ ] Ensure tests pass

2021-05-10 22:18 UTC, san983 approved these changes

2021-05-11 17:09 UTC, onlyhavecans requested changes
Do not mark files All Rights Reserved in this Apache Licenced Cookbook, that is only for internal cookbooks

This also is an API-breaking change with certificates. Can we break that change out into a separate PR so we can make it clear where this can break people's use of it?

2021-05-11 17:09 UTC, onlyhavecans commented on metadata.rb
> +chef_version '>= 16'
I think we should keep 15 support for now

2021-05-11 17:09 UTC, onlyhavecans commented on README.md
> +* Update your `expires_at` to be a parsable timestamp (see examples below)
The Resource Properties section needs updating as well

2021-05-12 19:37 UTC, AGS4NO commented on metadata.rb
> +chef_version '>= 16'
Set constraint to '>= 15'

2021-05-12 22:42 UTC, AGS4NO commented
@onlyhavecans I have broken the changes out for a separate release and locked the dnsimple gem version to be compatible with the current codebase.

2021-05-13 20:14 UTC, onlyhavecans approved these changes

2021-05-13 20:17 UTC, merged